# See https://github.com/canonical/gh-jira-sync-bot for config
settings:
  jira_project_key: "ISD"

  status_mapping:
    opened: Untriaged
    closed: done
    not_planned: rejected
    
  add_gh_comment: true
  
  components:
    - Ubuntu MOTD

  label_mapping:
    bug: Bug
    enhancement: Story
